steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project ${_SOURCE_PROJECT_ID}
        gcloud auth activate-service-account --key-file=/workspace/source-service-account-key.json
        gcloud compute instances describe ${_INSTANCE_NAME} --project ${_SOURCE_PROJECT_ID} --format=json > /workspace/instance_config.json

        sed -i 's/"project": "'${_SOURCE_PROJECT_ID}'"/"project": "'${_DESTINATION_PROJECT_ID}'"/g' /workspace/instance_config.json

        gcloud config set project ${_DESTINATION_PROJECT_ID}
        gcloud auth activate-service-account --key-file=/workspace/destination-service-account-key.json
        gcloud compute instances create testing-instance --project ${_DESTINATION_PROJECT_ID} --source-instance-config /workspace/instance_config.json

substitutions:
  _SOURCE_PROJECT_ID: 'ringed-hallway-427106-i4'
  _DESTINATION_PROJECT_ID: 'ap-project-2-428205'
  _INSTANCE_NAME: 'instance-20240701-112443'

# Add appropriate triggers and other configurations as needed
