steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Describing instance..."
        gcloud compute instances describe instance-20240701-112443 --project=ringed-hallway-427106-i4 --zone=us-central1-b --format=json > /workspace/instance-config.json
    id: 'describe-instance'
    dir: './'

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Modifying instance configuration for destination project..."
        sed -i 's/"ringed-hallway-427106-i4"/"ap-project-2-428205"/g' /workspace/instance-config.json
        instance_name=$(jq -r '.name' /workspace/instance-config.json)
        machine_type=$(jq -r '.machineType' /workspace/instance-config.json | awk -F/ '{print $NF}')
        source_image=$(jq -r '.disks[0].initializeParams.sourceImage' /workspace/instance-config.json)
        zone=$(jq -r '.zone' /workspace/instance-config.json | awk -F/ '{print $NF}')
        gcloud compute instances create ${instance_name}-copy --project=ap-project-2-428205 --zone=${zone} --machine-type=${machine_type} --source-image=${source_image}
    id: 'modify-and-create-instance'
    dir: './'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitution_option: 'ALLOW_LOOSE'
