steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'describe'
      - 'instance-20240701-112443'
      - '--project=ringed-hallway-427106-i4'
      - '--zone=us-central1-b'
    id: 'describe-instance'
    dir: './'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Copying instance configuration..."
        echo ${_INSTANCE_CONFIG} > /workspace/instance-config.json
    env:
      - 'INSTANCE_CONFIG=$(gcloud compute instances describe instance-20240701-112443 --project=ringed-hallway-427106-i4 --zone=us-central1-b --format=json)'
    id: 'copy-instance-config'
    dir: './'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Modifying instance configuration for destination project..."
        sed -i 's/ringed-hallway-427106-i4/ap-project-2-428205/g' /workspace/instance-config.json
    id: 'modify-instance-config'
    dir: './'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'testing-instance'
      - '--project=ap-project-2-428205'
      - '--zone=us-central1-b'
      - '--source-instance-config=/workspace/instance-config.json'
    id: 'create-new-instance'
    dir: './'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _INSTANCE_CONFIG: ''
