steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'describe'
      - 'instance-20240701-112443'
      - '--project=ringed-hallway-427106-i4'
      - '--zone=us-central1-b'
      - '--format=json'
    id: 'describe-instance'
    dir: './'
    stdout: 'instance-config.json'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Modifying instance configuration for destination project..."
        sed -i 's/"ringed-hallway-427106-i4"/"ap-project-2-428205"/g' instance-config.json
    id: 'modify-instance-config'
    dir: './'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'testing-instance'
      - '--project=ap-project-2-428205'
      - '--zone=us-central1-b'
      - '--source-instance-template=instance-config.json'
    id: 'create-new-instance'
    dir: './'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitution_option: 'ALLOW_LOOSE'
