steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project ${_SOURCE_PROJECT_ID}
        gcloud auth activate-service-account --key-file=/workspace/source-service-account-key.json
        gcloud compute instances describe ${_INSTANCE_NAME} --project ${_SOURCE_PROJECT_ID} --format=json > /workspace/instance_config.json

        sed -i 's/"project": "'${_SOURCE_PROJECT_ID}'"/"project": "'${_DESTINATION_PROJECT_ID}'"/g' /workspace/instance_config.json

        gcloud config set project ${_DESTINATION_PROJECT_ID}
        gcloud auth activate-service-account --key-file=/workspace/destination-service-account-key.json
        gcloud compute instances create ${_INSTANCE_NAME} --project ${_DESTINATION_PROJECT_ID} --source-instance-config /workspace/instance_config.json

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SOURCE_PROJECT_ID: 'source-project-id'
  _DESTINATION_PROJECT_ID: 'destination-project-id'
  _INSTANCE_NAME: 'instance-name'
