steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Describing instance..."
        gcloud compute instances describe instance-20240701-112443 --project=ringed-hallway-427106-i4 --zone=us-central1-b --format=json > /workspace/instance-config.json
        gcloud compute instance-templates create-from-instance temp-instance-template --source-instance=instance-20240701-112443 --source-instance-zone=us-central1-b --project=ringed-hallway-427106-i4
    id: 'describe-instance'
    dir: './'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating new instance..."
        gcloud compute instances create testing-instance --project=ap-project-2-428205 --zone=us-central1-b --source-instance-template=temp-instance-template
    id: 'create-new-instance'
    dir: './'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitution_option: 'ALLOW_LOOSE'
