steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud compute instances describe ${_SOURCE_INSTANCE_NAME} --zone=${_ZONE_NAME} &> /dev/null; then
          echo "Source instance ${_SOURCE_INSTANCE_NAME} exists. then stopping the instance....."
          STATUS=$(gcloud compute instances describe ${_SOURCE_INSTANCE_NAME} --zone=${_ZONE_NAME} --format="value(status)")
          echo "$STATUS"
        else
          echo "The source instance ${_SOURCE_INSTANCE_NAME} does not exist."
        fi
    id: 'check-instance'
    dir: './'    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud compute instances describe ${_TARGET_INSTANCE_NAME} --zone=${_ZONE_NAME} &> /dev/null; then                   
          echo "Instance ${_TARGET_INSTANCE_NAME} already exists."
        else                                          
          echo "Instance ${_TARGET_INSTANCE_NAME} does not exist. Deployment is processing......."
          gcloud compute instances create ${_TARGET_INSTANCE_NAME} \
            --project=${_TARGET_PROJECT_ID} \
            --zone=${_ZONE_NAME} \
            --machine-type=e2-medium \
            --service-account=1049980861600-compute@developer.gserviceaccount.com \
            --create-disk=auto-delete=yes,boot=yes,device-name=${_TARGET_INSTANCE_NAME}-disk,image=projects/${_SOURCE_PROJECT_ID}/global/images/image-deployment,mode=rw,size=50,type=projects/${_TARGET_PROJECT_ID}/zones/${_ZONE_NAME}/diskTypes/pd-balanced
          echo "Instance ${_TARGET_INSTANCE_NAME} is deployed successfully"
        fi
    id: 'create-instance'
    dir: './'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SOURCE_PROJECT_ID: 'ringed-hallway-427106-i4'
  _TARGET_PROJECT_ID: 'ap-project-2-428205'
  _SOURCE_INSTANCE_NAME: 'deployment-instance-dev'
  _TARGET_INSTANCE_NAME: 'deployment-instance-test'
  _ZONE_NAME: 'us-central1-a'
  STATUS
